---
- name: Deploy Nginx with Docker Swarm
  hosts: manager
  become: true

  tasks:
    - name: index.html
      get_url:
        url: https://www.nginx.com
        dest: /var/www/html

    - name: Set Docker Swarm service for Nginx
      docker_swarm_service:
        name: nginx_service
        image: nginx
        replicas: 1
        ports:
          - "8081:80"
        mounts:
          - source: /var/www/html
            target: /usr/share/nginx/html
            type: bind 
