---
- name: nginx 배포하기
  hosts: all  # Docker Swarm manager 노드를 지정합니다.
  become: true

  tasks:
    - name: nginx
      shell: docker service create --name mynginx --replicas 3 --constarint node.role==worker --with-registry-auth -p 8080:80 nginx
