---
- name: Deploy Nginx with Docker Swarm
  hosts: all  # Docker Swarm manager 노드를 지정합니다.
  become: true

  tasks:
    - name: Create Nginx service
      docker_swarm_service:
        name: nginx_service
        image: nginx:latest
        replicas: 3
        ports:
          - "8888:80"
        state: present

